In [1]:
import numpy as np


In [3]:
#np.+Tab 查看可用函數
np.abs? #使用信息

## 生产Numpy数组

### 从已有数据创建列表

In [13]:
#列表轉換爲ndarray
lst1=list()
lst1.append(1)
lst1.append(2)
nd1=np.array(lst1)
print(nd1)
print(type(nd1))

[1 2]
<class 'numpy.ndarray'>


In [12]:
#嵌套列表可以转换为多为数组ndarray
lst2=[[1,2],[3,4]]
nd2=np.array(lst2)
print(nd2)
print(type(nd2))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


### 利用random生成数据
#### 深度学习中为了有效提高模型性能,有些初始化需要满足一定的条件,可能需要生成一些满足正态分布或者均匀分布的数据.

In [27]:
nd3=np.random.random([3,3])
print("nd3的形状为:",nd3.shape,"\n",nd3)


nd3的形状为: (3, 3) 
 [[0.41092437 0.5796943  0.13995076]
 [0.40101756 0.62731701 0.32415089]
 [0.24475928 0.69475518 0.5939024 ]]


In [ ]:
# 为了每次都生成同一份数据,可以用seed制定一个随机种子,使用shuffle函数打乱生成的随机数.
np.random.seed(123)
nd4=np.random.randn(2,3) #randn是生成标准正态的随机数
print(nd4)
np.random.shuffle(nd4)
print("随机打乱后的随机数:\n",nd4,"\n",type(nd4))

### 创建特定形状的多维数组

In [29]:
# 可以使用np.zeros,np.ones,np.diag等来实现.也可以使用np.zeros_like,np.ones_like,np.empty_like
nd5=np.zeros([3,3])
print(np.ones_like(nd5))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [31]:
nd6=np.eye(3) #单位矩阵
print(nd6)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
nd7=np.diag([1,2,3])
print(nd7)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [34]:
# 将数据暂存在文本文件中,方便以后使用
nd8=np.random.random([5,5])
np.savetxt(X=nd8,fname="./test1.txt") #fname,指定file 的名字

In [35]:
#读取
nd9=np.loadtxt('./test1.txt')
print(nd9)

[[0.56843069 0.30254945 0.49730879 0.68326291 0.91669867]
 [0.10892895 0.49549179 0.23283593 0.43686066 0.75154299]
 [0.48089213 0.79772841 0.28270293 0.43341824 0.00975735]
 [0.34079598 0.68927201 0.86936929 0.26780382 0.45674792]
 [0.26828131 0.8370528  0.27051466 0.53006201 0.17537266]]


### 利用arange,linspace函数生成数组

In [37]:
#arange(start,stop,step,dtype=None) step可以是小数,不输入start和step,则默认为0和1
print(np.arange(10))
print(np.arange(0,5,0.5))

[0 1 2 3 4 5 6 7 8 9]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [42]:
#linspace是numpy模块中的常用函数,格式为:
#np.linspace(start,stop,num=50,endpoint=True,retstep=False,dtype=None)
print(np.linspace(0,1,10))#步长为(stop-start)/(num-1)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [43]:
print(np.logspace(0,1,10))

[ 1.          1.29154967  1.66810054  2.15443469  2.7825594   3.59381366
  4.64158883  5.9948425   7.74263683 10.        ]


## 获取元素

In [47]:
np.random.seed(2021)
nd10=np.random.random([10])
print(nd10,"\n")
#获取指定位置的元素
print(nd10[3],"\n")
#截取数据
print(nd10[3:6],"\n")
#截取固定间隔的数据,不包含end对应的数据
print(nd10[1:6:2],"\n") 
#倒序取数
print(nd10[::-2],"\n")

[0.60597828 0.73336936 0.13894716 0.31267308 0.99724328 0.12816238
 0.17899311 0.75292543 0.66216051 0.78431013] 

0.31267308385468695 

[0.31267308 0.99724328 0.12816238] 

[0.73336936 0.13894716 0.31267308 0.99724328 0.12816238] 

[0.78431013 0.75292543 0.12816238 0.31267308 0.73336936] 



In [58]:
#截取一个多维数组的一个区域内的数据
nd11=np.arange(25).reshape([5,5])
print(nd11[1:3,1:3],"\n")
#截取一个多维数组,其值在某一个范围以内
print(nd11[(nd11>3)&(nd11<10)],"\n")
#截取多维数组,指定的行,如读取第2,3行
print(nd11[[1,2]],"\n")
#或者
print(nd11[:,1:3],"\n")

print(nd11[2::2,::2])

[[ 6  7]
 [11 12]] 

[4 5 6 7 8 9] 

[[ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]
 [21 22]] 

[[10 12 14]
 [20 22 24]]


In [67]:
#除了以指定的索引来实现,还可以使用一些函数来实现
#random.choice从指定数据中随机抽取数据
from numpy import random as nr
a=np.arange(1,25,dtype=float) #查看类型用type,指定用dtype
print(a,"\n")

c1=nr.choice(a,size=(3,4)) #可以重复抽取
print(c1,"\n")

c2=nr.choice(a,size=(3,4),replace=False) #不可以重复抽取
print(c2,"\n")

c3=nr.choice(a,size=(3,4),p=a/np.sum(a)) #p为元素被抽取到的概率
print(c3)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24.] 

[[23. 18. 15. 12.]
 [24. 21. 21.  8.]
 [ 5.  4. 24. 13.]] 

[[13. 23.  1. 22.]
 [ 9. 20.  4. 18.]
 [17. 24.  7. 11.]] 

[[13. 11. 21.  9.]
 [20.  9.  9. 11.]
 [17. 21. 17. 13.]]


## Numpy的算数运算

In [69]:
### 对应元素相乘
A=np.array([[1,2],[3,4]])
B=np.array([[2,0],[3,4]])
print(A*B,"\n")

[[ 2  0]
 [ 9 16]] 



In [70]:
C=np.multiply(A,B)
print(C)

[[ 2  0]
 [ 9 16]]


In [72]:
#标量和数组相乘
print(A*2.0)

[[2. 4.]
 [6. 8.]]


In [73]:
print(A/2.0)

[[0.5 1. ]
 [1.5 2. ]]


In [74]:
#这样,就可以定义深度学习中的一些激活函数
X=np.random.rand(2,3)
def softmoid(x):
    return 1/(1+np.exp(-x))

def relu(x):
    return np.maximum(0,x)

def softmax(x):
    return np.exp(x)/np.sum(np.exp(x))

In [75]:
print("输入参数X的形状:\n",X.shape)
print("激活函数softmoid输出形状:\n",softmoid(X).shape)
print("激活函数relu输出形状:\n",relu(X).shape)
print("激活函数softmax输出形状:\n",softmax(X).shape)

输入参数X的形状:
 (2, 3)
激活函数softmoid输出形状:
 (2, 3)
激活函数relu输出形状:
 (2, 3)
激活函数softmax输出形状:
 (2, 3)


In [76]:
X1=np.array([[1,2],[3,4]])
X2=np.array([[5,6,7],[8,9,10]])
X3=np.dot(X1,X2)
print(X3)

[[21 24 27]
 [47 54 61]]


## 数组变形

In [82]:
#reshape改变向量的维度,但是不改变向量本身
arr1=np.arange(10)
print(arr1,"\n")
print(arr1.reshape(2,5),"\n")
print(arr1.reshape(5,-1),"\n")
print(arr1.reshape(-1,5),"\n")
print(arr1,"\n")

[0 1 2 3 4 5 6 7 8 9] 

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[0 1 2 3 4 5 6 7 8 9] 



In [86]:
#resize改变向量维度,也修改向量本身
arr2=np.arange(10)
print(arr2,"\n")
arr2.resize(2,5) #直接print这句话,会返回None
print(arr2,"\n")

[0 1 2 3 4 5 6 7 8 9] 

[[0 1 2 3 4]
 [5 6 7 8 9]] 



In [88]:
#转置
arr3=np.arange(12).reshape(3,4) #同样,此处用resize会报错#
print(arr3,"\n")
print(arr3.T,"\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]] 



In [93]:
#ravel向量展平,不会产生原数组的副本
arr4=np.arange(6).reshape(2,-1)
print(arr4,"\n")
print("优先按照列展平\n",arr4.ravel('F'))
print("\n优先按照行展平\n",arr4.ravel())

[[0 1 2]
 [3 4 5]] 

优先按照列展平
 [0 3 1 4 2 5]

优先按照行展平
 [0 1 2 3 4 5]


In [101]:
#flatten 把矩阵转换为向量,这种需求通常出现在卷积网络和全链接层之间,返回元数组的副本
arr5=np.floor(10*np.random.random((3,4)))
print(arr5,'\n')
print(arr5.flatten())

[[0. 0. 4. 4.]
 [6. 9. 5. 9.]
 [9. 4. 6. 8.]] 

[0. 0. 4. 4. 6. 9. 5. 9. 9. 4. 6. 8.]


In [109]:
#squeeze用来降维的函数,把矩阵中的1去掉
arr6=np.arange(3).reshape(3,1)
print(arr6.shape,'\n')
print(arr6.squeeze().shape,'\n')
arr7=np.arange(6).reshape(3,1,2,1)
print(arr7.shape,'\n')
print(arr7.squeeze().shape,'\n')

(3, 1) 

(3,) 

(3, 1, 2, 1) 

(3, 2) 



In [115]:
#transpose对高维矩阵进行轴变换.
arr8=np.arange(24).reshape(2,3,4)
print(arr8.shape)
print(arr8.transpose(0,2,1).shape)

(2, 3, 4)
(2, 4, 3)


## 合并数组

In [119]:
#append,concatenate,stack都有一个axis参数,用于确定按什么方式合并
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.append(a,b)
print(c)

[1 2 3 4 5 6]


In [120]:
a=np.arange(4).reshape(2,2)
b=np.arange(4).reshape(2,2)
#按照行合并,行数增加
c=np.append(a,b,axis=0)
#按照列合并,列数增加
d=np.append(a,b,axis=1)
print(c,"\n")
print(d,"\n")

[[0 1]
 [2 3]
 [0 1]
 [2 3]] 

[[0 1 0 1]
 [2 3 2 3]] 



In [128]:
#concatenate,沿着指定轴进行链接数据或者矩阵.默认按照行合并
a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
c=np.concatenate((a,b),axis=0)
print(c,"\n")
d=np.concatenate((a,b.T),axis=1)
print(d,'\n')

[[1 2]
 [3 4]
 [5 6]] 

[[1 2 5]
 [3 4 6]] 



In [136]:
#沿着轴堆叠数组或者矩阵
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.stack((a,b),axis=2))

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


## 批量处理

In [139]:
#mini_batch
data_train=np.random.randn(10000,2,3)
print(data_train.shape,"\n")

np.random.shuffle(data_train)

#定义批量大小
batch_size=100

#进行批处理
for i in range(0,len(data_train),batch_size):
    x_batch_sum=np.sum(data_train[i:i+batch_size])
    print("第{}批次,该批次的数据之和为:{}".format(i,x_batch_sum))


(10000, 2, 3) 

第0批次,该批次的数据之和为:21.11134570109606
第100批次,该批次的数据之和为:34.14758322719199
第200批次,该批次的数据之和为:17.799166736439886
第300批次,该批次的数据之和为:23.11671282422046
第400批次,该批次的数据之和为:-23.242215724403806
第500批次,该批次的数据之和为:8.788810231917186
第600批次,该批次的数据之和为:-32.05085352900657
第700批次,该批次的数据之和为:-37.587594623300944
第800批次,该批次的数据之和为:3.9343178026236476
第900批次,该批次的数据之和为:-0.821688934029833
第1000批次,该批次的数据之和为:14.868065097000148
第1100批次,该批次的数据之和为:13.28797311668437
第1200批次,该批次的数据之和为:-0.03446779142348788
第1300批次,该批次的数据之和为:-49.98350841525306
第1400批次,该批次的数据之和为:-0.041261675489973726
第1500批次,该批次的数据之和为:-6.572969763395881
第1600批次,该批次的数据之和为:-4.5167555845611655
第1700批次,该批次的数据之和为:-59.78406815484988
第1800批次,该批次的数据之和为:5.9284493786307575
第1900批次,该批次的数据之和为:43.93031099836854
第2000批次,该批次的数据之和为:-13.301149103775717
第2100批次,该批次的数据之和为:-12.655169085484488
第2200批次,该批次的数据之和为:4.509171123834525
第2300批次,该批次的数据之和为:-18.85416917755785
第2400批次,该批次的数据之和为:9.99581314151058
第2500批次,该批次的数据之和为:-39.41462472876423
第2600批次,该批次的数据之和为:-14.13378094640

## 通用函数ufunc

In [140]:
#ufunc 支持ndarry相关计算,实现速度较快
#可以通过一下代码来比较
import time 
import math 
import numpy as np

In [142]:
x=[i*0.001 for i in range(1000000)]
# start=time.clock() Python 3.8 已移除 clock() 方法 
#可以使用 time.perf_counter() 或 time.process_time() 方法替代。
start=time.process_time()
for i,t in enumerate(x):
    x[i]=math.sin(t)
print("math.sin: ",time.process_time()-start)

math.sin:  0.15694367700000011


In [144]:
x=[i*0.001 for i in range(1000000)]
# start=time.clock() Python 3.8 已移除 clock() 方法 
#可以使用 time.perf_counter() 或 time.process_time() 方法替代。
x=np.array(x)
start=time.process_time()
np.sin(x)
print("numpy.sin: ",time.process_time()-start)

numpy.sin:  0.010448773000000244


In [147]:
x1=np.random.rand(1000000)
x2=np.random.rand(1000000)

#使用循环计算向量点积
tic=time.process_time()
dot=0
for i in range(len(x1)):
    dot+=x1[i]*x2[i]
toc=time.process_time()
print("dot= "+str(dot)+"\n for loop----- Computation time =" +str(1000*(toc-tic))+"ms")

#使用numpy函数求点积
tic=time.process_time()
dot=0
dot=np.dot(x1,x2)
toc=time.process_time()
print("dot= "+str(dot)+"\n vector version----- Computation time =" +str(1000*(toc-tic))+"ms")


dot= 250161.6666350324
 for loop----- Computation time =290.5144220000011ms
dot= 250161.66663503615
 vector version----- Computation time =3.1715410000003885ms


## 广播机制

In [148]:
A=np.arange(0,40,10).reshape(4,1)
B=np.arange(0,3)

print("A矩阵的形状:{},B矩阵的形状:{}".format(A.shape,B.shape))
C=A+B
print("C矩阵的形状:{}".format(C.shape))
print(C)

A矩阵的形状:(4, 1),B矩阵的形状:(3,)
C矩阵的形状:(4, 3)
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
